lib: mat.c vvod.c multi.c dedu.c summ.c 
	gcc vvod.c -o libvvod.so -shared -fPIC 
	gcc dedu.c -o libdedu.so -shared -fPIC
	gcc summ.c -o libsumm.so -shared -fPIC
	gcc multi.c -o libmulti.so -shared -fPIC
	gcc mat.c -o libdiv.so -shared -fPIC	
